### ISSUE TITLE
At most 50 records get returned

### ISSUE THREAD

**Issue by wlievens** [sonatype-nexus-community/repo-diff#1]
I tried out the script, but on my Nexus repositories (both the pypi proxy and the hosted one), only 50 records get returned. It seems liket he rest API endpoint cuts off search results at 50. Is there a workaround for this, or is this a configuration issue with nexus?

**Comment by wlievens** [comment]
https://help.sonatype.com/repomanager3/rest-and-integration-api/pagination

It seems like this might be built-in pagination? Is there an API option to bypass this or should the script be extended to exhaust the pagination?

**Comment by wlievens** [comment]
I managed to adapt the script to follow the `continuationToken` so as to exhaust the entire listing (it still definitely runs fast enough).

I recommend you do the same. I would contribute my changes, but I've since made some other formatting and content changes to the script which means it's probably less work for you to just implement the same change and retain your source.

**Comment by bac** [comment]
I attempted to use the continuationToken but it does not work.  The previous tokens seem to cycle.

@wlievens would you mind sharing a snippet of your solution for that part?

**Comment by bac** [comment]
Here is a snippet of the change I made to get pagination to work:

```
    continuation_token = ""
    baseurl = (
        f"{REPO_HOSTNAME}/service/rest/v1/search/?sort=name&repository={repo_name}"
    )
    while continuation_token is not None:
        url = baseurl
        if continuation_token:
            url += f"&continuationToken={continuation_token}"
        response = requests.get(url, auth=(USER, TOKEN))
        response.raise_for_status()
        res = json.loads(response.text)
        continuation_token = res["continuationToken"]
```

**Comment by Iletee** [comment]
Yes, thats a pagination issue - we'll get on it

**Comment by za** [comment]
Hi @Iletee is there a way to get the latest `continuationToken` without having to go through each of it? I'd like to know how many pages the repo has.

Something with Python if you go to the last index with `data[-1]`.
