### ISSUE TITLE
Nexus2

### ISSUE THREAD

**Issue by masterlexa** [sonatype-nexus-community/repo-diff#2]
How to check nexus2?

**Comment by Iletee** [comment]
Hi, this script is aimed at nexus 3 and using any running instance using the REST API. In NX2 the apis are more restricted with non-maven ecosystems which are the ones most affected by this.

To check proxies vs hosted in nxrm2 the lowest friction approach will be to compare directories in sonatype-work/storage/repo-name1 vs sonatype-work/storage/repo-name2 for collisions. 

We'll look into a nx2 admin script to help but would recommend investigating upgrading to nx3 as a part of this
